# Generated by Django 4.2.5 on 2023-09-26 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente'),
        ),
    ]
