# Generated by Django 4.2.5 on 2023-09-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pessoa_insta_alter_pessoa_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='serie',
        ),
    ]
